#!/usr/bin/env python3
"""Audit cached v8asm binaries and sibling startup snapshots.

The bin cache stores v8asm build artifacts. Its sibling snapshot_blob.bin must
be the snapshot generated by that v8asm build, not an Electron/Node embedder
snapshot used for external forced-disasm tests.
"""

from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_BIN_CACHE = ROOT / "tests" / "decomp_rounds" / "bin_cache"
DEFAULT_V8_OUT = Path("/home/aynakeya/workspace/tmp/v8test/v8/out")
DEFAULT_ELECTRON_CACHE = Path("/home/aynakeya/workspace/tmp/v8test/electron-cache")


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def snapshot_version(path: Path) -> str:
    # Keep this in sync with v8patch/main.cc. V8's startup snapshot header
    # moved across major versions, so a single hard-coded offset can turn a
    # same-build snapshot into a misleading cross-version hint.
    blob = path.read_bytes()
    for offset in (16, 12, 8):
        data = blob[offset : offset + 64]
        hint = data.split(b"\0", 1)[0].decode("latin1", "replace")
        if is_plausible_snapshot_version(hint):
            return hint
    return ""


def is_plausible_snapshot_version(hint: str) -> bool:
    if not hint or not hint[0].isdigit() or "." not in hint:
        return False
    return all(c.isalnum() or c in ".-+_" for c in hint)


def collect_known_snapshots(v8_out: Path, electron_cache: Path) -> dict[str, list[str]]:
    known: dict[str, list[str]] = {}
    for base, label in ((v8_out, "v8-out"), (electron_cache, "electron-cache")):
        if not base.exists():
            continue
        for name in ("snapshot_blob.bin", "v8_context_snapshot.bin"):
            for path in base.rglob(name):
                known.setdefault(sha256(path), []).append(f"{label}:{path}")
    return known


def run_metadata(v8asm: Path, cmd: str, cwd: Path) -> tuple[int, list[str], list[str]]:
    proc = subprocess.run(
        [str(v8asm), cmd],
        cwd=cwd,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=20,
        check=False,
    )
    return proc.returncode, proc.stdout.splitlines(), proc.stderr.splitlines()


def is_noisy(lines: list[str]) -> bool:
    return any(
        "v8asm:" in line or "Warning:" in line or "snapshot" in line.lower()
        for line in lines
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bin-cache", type=Path, default=DEFAULT_BIN_CACHE)
    parser.add_argument("--v8-out", type=Path, default=DEFAULT_V8_OUT)
    parser.add_argument("--electron-cache", type=Path, default=DEFAULT_ELECTRON_CACHE)
    parser.add_argument("--strict", action="store_true")
    args = parser.parse_args()

    known_snapshots = collect_known_snapshots(args.v8_out, args.electron_cache)
    problems: list[str] = []
    warnings: list[str] = []

    cache_dirs = [
        p for p in sorted(args.bin_cache.iterdir()) if p.is_dir() and p.name.startswith("v8asm.")
    ]
    print(f"checked_dirs={len(cache_dirs)}")
    for cache_dir in cache_dirs:
        rel = cache_dir.relative_to(ROOT)
        print(f"== {rel} ==")
        v8asm = cache_dir / "v8asm"
        if not v8asm.exists():
            problems.append(f"{rel}: missing v8asm")
            print("missing v8asm")
            continue

        binary_version = ""
        for cmd in ("version", "build-args"):
            rc, stdout, stderr = run_metadata(v8asm, cmd, cache_dir)
            print(
                f"{cmd}: rc={rc} stdout_lines={len(stdout)} "
                f"stderr_lines={len(stderr)} first={stdout[0] if stdout else ''!r}"
            )
            if cmd == "version" and stdout:
                binary_version = stdout[-1]
            if rc != 0 or stderr or is_noisy(stdout + stderr):
                problems.append(
                    f"{rel}: {cmd} is noisy or failed "
                    f"(rc={rc}, stdout_lines={len(stdout)}, stderr_lines={len(stderr)})"
                )

        snapshot = cache_dir / "snapshot_blob.bin"
        if not snapshot.exists():
            problems.append(f"{rel}: missing snapshot_blob.bin")
            print("snapshot_blob: missing")
        else:
            digest = sha256(snapshot)
            hint = snapshot_version(snapshot)
            matches = known_snapshots.get(digest, [])
            print(
                f"snapshot_blob: size={snapshot.stat().st_size} "
                f"version_hint={hint!r} sha256={digest[:16]} matches={len(matches)}"
            )
            for match in matches[:3]:
                print(f"  match: {match}")
            if any(m.startswith("electron-cache:") for m in matches) and not any(
                m.startswith("v8-out:") for m in matches
            ):
                problems.append(f"{rel}: snapshot_blob.bin matches Electron release cache")
            if matches and not any(m.startswith("v8-out:") for m in matches):
                warnings.append(f"{rel}: snapshot_blob.bin has no visible V8 out match")
            if binary_version and hint and hint[0].isdigit() and not hint.startswith(binary_version):
                problems.append(
                    f"{rel}: snapshot version hint {hint!r} does not match binary {binary_version!r}"
                )

        context_snapshot = cache_dir / "v8_context_snapshot.bin"
        if context_snapshot.exists():
            problems.append(f"{rel}: bin cache must not contain v8_context_snapshot.bin")
            print("v8_context_snapshot: present")
        print()

    if warnings:
        print("WARNINGS")
        for warning in warnings:
            print(f"- {warning}")
    if problems:
        print("PROBLEMS")
        for problem in problems:
            print(f"- {problem}")
        return 1
    print("bin_cache_ok=1")
    return 0


if __name__ == "__main__":
    sys.exit(main())
