#!/usr/bin/env python3
"""Validate Electron-generated bytenode caches with matching Electron v8asm.

The gate only uses Electron releases that are already present in the local
electron-cache directory. Each release is matched to a cached v8asm by the exact
`process.versions.v8` string so Electron/bytenode caches are not mixed across
V8 baselines.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ELECTRON_CACHE = Path("/home/aynakeya/workspace/tmp/v8test/electron-cache")
DEFAULT_BIN_CACHE = ROOT / "tests/decomp_rounds/bin_cache"
DEFAULT_BYTENODE = Path("/home/aynakeya/.npm/_npx/ea56e60f3ac75570/node_modules/bytenode")
DEFAULT_OUT = ROOT / "tests/decomp_rounds/electron_matrix"

CRASH_NEEDLES = (
    "Fatal error",
    "FailureMessage",
    "Check failed",
    "CHECK failed",
    "DCHECK failed",
    "Segmentation fault",
    "Received signal",
    "fixed_offset",
    "Traceback",
)

SOURCE = """\
function calc(a, b, c) {
  const x = a + b;
  return (x + c) * 2;
}
globalThis.answer = calc(1, 2, 3);
"""


def run(
    argv: list[str],
    *,
    out: Path | None = None,
    err: Path | None = None,
    env: dict[str, str] | None = None,
) -> subprocess.CompletedProcess[str]:
    proc = subprocess.run(
        argv,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=env,
        check=False,
    )
    if out is not None:
        out.write_text(proc.stdout, encoding="utf-8", errors="ignore")
    if err is not None:
        err.write_text(proc.stderr, encoding="utf-8", errors="ignore")
    return proc


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def has_crash(*paths: Path) -> bool:
    for path in paths:
        if not path.exists():
            continue
        text = read_text(path)
        if any(needle in text for needle in CRASH_NEEDLES):
            return True
    return False


def count_quality(path: Path) -> tuple[int, int, int]:
    if not path.exists():
        return (0, 0, 0)
    raw = unknown = undef = 0
    for line in read_text(path).splitlines():
        stripped = line.strip()
        if stripped.startswith("goto offset_") or (
            stripped.startswith("if (") and " goto offset_" in stripped
        ):
            raw += 1
        if stripped.startswith("// 0x") and " @ " in stripped:
            unknown += 1
        if "<undefined: segmentfault" in line:
            undef += 1
    return raw, unknown, undef


def status(code: int) -> str:
    return "ok" if code == 0 else f"fail:{code}"


def electron_info(electron: Path) -> dict[str, str]:
    env = os.environ.copy()
    env["ELECTRON_RUN_AS_NODE"] = "1"
    proc = run(
        [
            str(electron),
            "-e",
            (
                "console.log(JSON.stringify({"
                "electron:process.versions.electron,"
                "v8:process.versions.v8,"
                "arch:process.arch"
                "}));"
            ),
        ],
        env=env,
    )
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr or proc.stdout)
    return json.loads(proc.stdout)


def v8asm_metadata(v8asm: Path) -> tuple[str, str]:
    version = run([str(v8asm), "version"])
    build_args = run([str(v8asm), "build-args"])
    if version.returncode != 0 or build_args.returncode != 0:
        raise RuntimeError(f"metadata failed for {v8asm}")
    return version.stdout.strip().splitlines()[-1], ";".join(build_args.stdout.splitlines())


def electron_dirs(base: Path) -> list[Path]:
    if not base.exists():
        return []
    return sorted(
        path
        for path in base.iterdir()
        if (path / "electron").is_file()
        and (path / "snapshot_blob.bin").is_file()
        and (path / "v8_context_snapshot.bin").is_file()
    )


def cached_v8asms(base: Path) -> list[Path]:
    if not base.exists():
        return []
    return sorted(path for path in base.glob("*/v8asm") if path.is_file() and os.access(path, os.X_OK))


def select_matching_bins(electron_v8: str, bins: list[Path]) -> list[Path]:
    exact: list[Path] = []
    for bin_path in bins:
        try:
            version, _ = v8asm_metadata(bin_path)
        except RuntimeError:
            continue
        if version == electron_v8 and "electron" in bin_path.parent.name:
            exact.append(bin_path)
    preferred = [path for path in exact if "nostaticroots" not in path.parent.name]
    return preferred or exact


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--electron-cache", type=Path, default=DEFAULT_ELECTRON_CACHE)
    parser.add_argument("--bin-cache", type=Path, default=DEFAULT_BIN_CACHE)
    parser.add_argument("--bytenode", type=Path, default=DEFAULT_BYTENODE)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--max-raw-goto", type=int, default=0)
    parser.add_argument("--max-unknown", type=int, default=0)
    args = parser.parse_args()

    bytenode = args.bytenode.resolve()
    if not (bytenode / "lib/index.js").is_file():
        raise SystemExit(f"bytenode not found: {bytenode}")

    out_dir = args.out.resolve()
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    electron_releases = electron_dirs(args.electron_cache.resolve())
    bins = cached_v8asms(args.bin_cache.resolve())
    failures: list[str] = []
    warnings: list[str] = []
    rows: list[str] = []

    if not electron_releases:
        failures.append(f"no Electron releases found under {args.electron_cache}")

    for electron_dir in electron_releases:
        electron = electron_dir / "electron"
        info = electron_info(electron)
        electron_v8 = info["v8"]
        electron_version = info["electron"]
        matches = select_matching_bins(electron_v8, bins)
        if not matches:
            failures.append(f"{electron_dir.name}: no matching Electron v8asm for {electron_v8}")
            continue

        case_dir = out_dir / electron_dir.name
        case_dir.mkdir(parents=True)
        source = case_dir / "electron-case.js"
        jsc = case_dir / "electron-case.jsc"
        source.write_text(SOURCE, encoding="utf-8")

        env = os.environ.copy()
        env["ELECTRON_RUN_AS_NODE"] = "1"
        compile_proc = run(
            [
                str(electron),
                "-e",
                (
                    "const b=require(process.argv[1]);"
                    "b.compileFile({filename:process.argv[2],output:process.argv[3]});"
                ),
                str(bytenode),
                str(source),
                str(jsc),
            ],
            out=case_dir / "compile.out",
            err=case_dir / "compile.err",
            env=env,
        )
        if compile_proc.returncode != 0 or not jsc.exists():
            failures.append(f"{electron_dir.name}: bytenode compile {status(compile_proc.returncode)}")
            continue

        for bin_path in matches:
            version, build_args = v8asm_metadata(bin_path)
            bin_label = bin_path.parent.name
            for snapshot_label in ("snapshot_blob", "v8_context_snapshot"):
                snapshot = electron_dir / f"{snapshot_label}.bin"
                if snapshot_label == "snapshot_blob":
                    snapshot = electron_dir / "snapshot_blob.bin"
                work = case_dir / bin_label / snapshot_label
                work.mkdir(parents=True)
                check_out = work / "checkversion.out"
                check_err = work / "checkversion.err"
                dis_txt = work / "disasm.txt"
                dis_err = work / "disasm.err"
                dec_js = work / "decompiled.l4.js"
                dec_err = work / "decompile.err"

                check_proc = run(
                    [
                        str(bin_path),
                        "--snapshot_blob",
                        str(snapshot),
                        "checkversion",
                        str(jsc),
                        "--force-incompatible",
                    ],
                    out=check_out,
                    err=check_err,
                )
                dis_proc = run(
                    [
                        str(bin_path),
                        "--snapshot_blob",
                        str(snapshot),
                        "disasm",
                        str(jsc),
                        "--force-incompatible",
                    ],
                    out=dis_txt,
                    err=dis_err,
                )
                dec_proc = subprocess.CompletedProcess([], 1)
                if dis_proc.returncode == 0:
                    dec_proc = run(
                        [
                            sys.executable,
                            str(ROOT / "decompiler/v8decompiler.py"),
                            str(dis_txt),
                            "--level",
                            "4",
                            "--runtime",
                        ],
                        out=dec_js,
                        err=dec_err,
                    )

                raw, unknown, undef = count_quality(dec_js)
                crash = has_crash(check_out, check_err, dis_txt, dis_err, dec_err)
                row = (
                    f"| `{electron_dir.name}` | `{electron_version}` | `{electron_v8}` | "
                    f"`{bin_label}` | `{version}` | `{build_args}` | `{snapshot_label}` | "
                    f"{status(check_proc.returncode)} | {status(dis_proc.returncode)} | "
                    f"{status(dec_proc.returncode)} | raw:{raw} unknown:{unknown} undef:{undef} | "
                    f"{'yes' if crash else 'no'} |"
                )
                rows.append(row)

                prefix = f"{electron_dir.name} {bin_label} {snapshot_label}"
                if check_proc.returncode != 0:
                    failures.append(f"{prefix}: checkversion {status(check_proc.returncode)}")
                if dis_proc.returncode != 0:
                    failures.append(f"{prefix}: disasm {status(dis_proc.returncode)}")
                if dec_proc.returncode != 0:
                    failures.append(f"{prefix}: decompile {status(dec_proc.returncode)}")
                if crash:
                    failures.append(f"{prefix}: crash signature detected")
                if raw > args.max_raw_goto:
                    failures.append(f"{prefix}: raw_goto={raw} > {args.max_raw_goto}")
                if unknown > args.max_unknown:
                    failures.append(f"{prefix}: unknown={unknown} > {args.max_unknown}")
                if undef:
                    warnings.append(f"{prefix}: undefined_fallbacks={undef}")

    summary = out_dir / "summary.md"
    with summary.open("w", encoding="utf-8") as f:
        f.write("# Electron v8asm Matrix\n\n")
        f.write(f"- electron_cache: `{args.electron_cache}`\n")
        f.write(f"- bin_cache: `{args.bin_cache}`\n")
        f.write(f"- bytenode: `{bytenode}`\n")
        f.write(f"- releases: `{len(electron_releases)}`\n\n")
        f.write("| electron_dir | electron | electron_v8 | v8asm | v8asm_version | build_args | snapshot | checkversion | disasm | decompile | quality | crash |\n")
        f.write("|---|---:|---:|---|---:|---|---|---:|---:|---:|---:|---:|\n")
        for row in rows:
            f.write(row + "\n")
        f.write("\n## Gate Summary\n\n")
        f.write(f"- warnings: {len(warnings)}\n")
        for warning in warnings:
            f.write(f"  - {warning}\n")
        f.write(f"- failures: {len(failures)}\n")
        for failure in failures:
            f.write(f"  - {failure}\n")

    print(f"Done. Summary: {summary}")
    if failures:
        print("Gate failures:", file=sys.stderr)
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        return 1
    print("electron_version_matrix_ok=1")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
