#!/usr/bin/env python3
"""Exercise an Electron-generated bytenode cache with Electron snapshots.

This focused guard checks startup snapshot compatibility. A failure such as
`Check failed: true == fixed_offset` means the v8asm binary was compiled with a
different static-roots setting than the snapshot being loaded.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_V8ASM = (
    ROOT
    / "tests/decomp_rounds/bin_cache/v8asm.13.2.152.41.electron.x64.release/v8asm"
)
DEFAULT_ELECTRON_DIR = (
    Path("/home/aynakeya/workspace/tmp/v8test/electron-cache/v34.3.0-linux-x64")
)
DEFAULT_BYTENODE = Path(
    "/home/aynakeya/.npm/_npx/ea56e60f3ac75570/node_modules/bytenode"
)
DEFAULT_OUT = Path("/tmp/v8asm-electron-snapshot-round")

CRASH_NEEDLES = (
    "Fatal error",
    "FailureMessage",
    "Check failed",
    "CHECK failed",
    "DCHECK failed",
    "Segmentation fault",
    "Received signal",
    "fixed_offset",
    "Traceback",
)

SOURCE = """\
function calc(a, b, c) {
  const x = a + b;
  return (x + c) * 2;
}
globalThis.answer = calc(1, 2, 3);
"""


def run(
    argv: list[str],
    *,
    out: Path | None = None,
    err: Path | None = None,
    stdin: str | None = None,
    env: dict[str, str] | None = None,
) -> subprocess.CompletedProcess[str]:
    proc = subprocess.run(
        argv,
        input=stdin,
        text=True,
        capture_output=True,
        env=env,
        check=False,
    )
    if out is not None:
        out.write_text(proc.stdout, encoding="utf-8", errors="ignore")
    if err is not None:
        err.write_text(proc.stderr, encoding="utf-8", errors="ignore")
    return proc


def has_crash(*paths: Path) -> bool:
    for path in paths:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        if any(needle in text for needle in CRASH_NEEDLES):
            return True
    return False


def require_file(path: Path, label: str) -> None:
    if not path.is_file():
        raise SystemExit(f"{label} not found: {path}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--v8asm", type=Path, default=DEFAULT_V8ASM)
    parser.add_argument("--electron-dir", type=Path, default=DEFAULT_ELECTRON_DIR)
    parser.add_argument("--bytenode", type=Path, default=DEFAULT_BYTENODE)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    v8asm = args.v8asm.resolve()
    electron_dir = args.electron_dir.resolve()
    electron = electron_dir / "electron"
    bytenode = args.bytenode.resolve()
    out_dir = args.out.resolve()
    snapshot_blob = electron_dir / "snapshot_blob.bin"
    context_snapshot = electron_dir / "v8_context_snapshot.bin"

    require_file(v8asm, "v8asm")
    require_file(electron, "electron")
    require_file(bytenode / "lib/index.js", "bytenode")
    require_file(snapshot_blob, "snapshot_blob.bin")
    require_file(context_snapshot, "v8_context_snapshot.bin")

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    source = out_dir / "electron-case.js"
    jsc = out_dir / "electron-case.jsc"
    source.write_text(SOURCE, encoding="utf-8")

    electron_version = "unknown"
    version_file = electron_dir / "version"
    if version_file.exists():
        electron_version = version_file.read_text(encoding="utf-8").strip()
    metadata = [
        f"v8asm={v8asm}",
        f"electron={electron}",
        f"electron_version={electron_version}",
        f"bytenode={bytenode}",
        f"snapshot_blob={snapshot_blob}",
        f"v8_context_snapshot={context_snapshot}",
    ]
    (out_dir / "metadata.txt").write_text("\n".join(metadata) + "\n", encoding="utf-8")

    env = os.environ.copy()
    env["ELECTRON_RUN_AS_NODE"] = "1"
    compile_proc = run(
        [
            str(electron),
            "-e",
            (
                "const b=require(process.argv[1]);"
                "b.compileFile({filename:process.argv[2],output:process.argv[3]});"
            ),
            str(bytenode),
            str(source),
            str(jsc),
        ],
        out=out_dir / "compile.out",
        err=out_dir / "compile.err",
        env=env,
    )
    if compile_proc.returncode != 0 or not jsc.exists():
        print(f"electron compile failed: rc={compile_proc.returncode}", file=sys.stderr)
        return 1

    failures: list[str] = []
    for label, snapshot in (
        ("snapshot_blob", snapshot_blob),
        ("v8_context_snapshot", context_snapshot),
    ):
        dis_txt = out_dir / f"{label}.disasm.txt"
        dis_err = out_dir / f"{label}.disasm.err"
        dec_js = out_dir / f"{label}.dec.l4.js"
        dec_err = out_dir / f"{label}.decompile.err"
        check_out = out_dir / f"{label}.checkversion.out"
        check_err = out_dir / f"{label}.checkversion.err"

        check_proc = run(
            [
                str(v8asm),
                "--snapshot_blob",
                str(snapshot),
                "checkversion",
                str(jsc),
                "--force-incompatible",
            ],
            out=check_out,
            err=check_err,
        )
        dis_proc = run(
            [
                str(v8asm),
                "--snapshot_blob",
                str(snapshot),
                "disasm",
                str(jsc),
                "--force-incompatible",
            ],
            out=dis_txt,
            err=dis_err,
        )
        dec_proc = subprocess.CompletedProcess([], 1)
        if dis_proc.returncode == 0:
            dec_proc = run(
                [
                    sys.executable,
                    str(ROOT / "decompiler/v8decompiler.py"),
                    str(dis_txt),
                    "--level",
                    "4",
                    "--runtime",
                ],
                out=dec_js,
                err=dec_err,
            )

        if check_proc.returncode != 0:
            failures.append(f"{label}: checkversion rc={check_proc.returncode}")
        if dis_proc.returncode != 0:
            failures.append(f"{label}: disasm rc={dis_proc.returncode}")
        if dec_proc.returncode != 0:
            failures.append(f"{label}: decompile rc={dec_proc.returncode}")
        if has_crash(check_out, check_err, dis_txt, dis_err, dec_err):
            failures.append(f"{label}: crash signature detected")

        print(
            f"{label}: checkversion={check_proc.returncode} "
            f"disasm={dis_proc.returncode} decompile={dec_proc.returncode}"
        )

    if failures:
        print("FAILURES:", file=sys.stderr)
        for failure in failures:
            print(f"- {failure}", file=sys.stderr)
        print(f"output={out_dir}", file=sys.stderr)
        return 1

    print(f"electron_snapshot_round_ok=1 output={out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
